### ISSUE TITLE
Top bar icon disappears

### ISSUE THREAD

**Issue by Vultilion** [actuallymentor/battery#109]
Whenever the % next to the original battery icon is activated, the icon of the battery-limiter is not visible.

**Comment by earthsound** [comment]
@Vultilion do you have a MBP with a notch? If so, it may be hidden due to too many icons in the menu bar. If you have enough room it should show. 
<img width="98" alt="image" src="https://user-images.githubusercontent.com/2745903/225135906-e4a4a511-47c0-4859-8307-551568f1e807.png">

There are a few options:

- Close apps that have icons in the menu bar
- Hide the menu bar icon for apps that allow it
- Use a tool (e.g., [Hidden Bar](https://github.com/dwarvesf/hidden), [iBar](https://apps.apple.com/us/app/ibar-menubar-icon-control-tool/id6443843900), and [Bartender](https://www.macbartender.com/)) that provides more options for autohiding/showing menu bar icons.

**Comment by actuallymentor** [comment]
Thanks for responding to this @earthsound
