### ISSUE TITLE
limiting charging below 80

### ISSUE THREAD

**Issue by pranaystark** [actuallymentor/battery#115]
just wanted know if i limit charging below 80 say 70 always will there be any issues?

**Comment by PatiB87** [comment]
I even use 50-60 but you have to set it via CLI of course.

**Comment by lilianmoraru** [comment]
Yes, it's fine. 50-60% is technically ideal but 80% is usually suggested because it's a good balance between battery health and how often you need to charge so it's not too bothersome.
I personally use 70% at home.
Commercial electric sea ferries like Forsea Ferries for example charges to 2/3(66%) and discharge to 42%(they say that they prefer not to go below 42%) to prolong battery life.
