### ISSUE TITLE
Error installing battery limiter: Command failed: ./applet /bin/sh: ./applet: Bad CPU type in executable

### ISSUE THREAD

**Issue by jxnding** [actuallymentor/battery#16]
After installing, on first-time launch, I get 2 errors:

Error installing battery limiter: Command failed: ./applet
/bin/sh: ./applet: Bad CPU type in executable

Battery limiter error: Command failed: PATH=$PATH:/usr/local/bin/battery battery status
/bin/bash: battery: command not found

I'm on Ventura 13.0 beta, installed the dmg battery-1.0.3-arm64.dmg

**Comment by jxnding** [comment]
Same with brew install battery. However the CLI works kinda (I suspect because it compiles from source right?)

However, it's not working very well. Typing "battery status" gives:
touch: /Users/ding/.battery/battery.log: Permission denied

**Comment by jxnding** [comment]
No, I am on an M1 Macbook Air.

**Comment by actuallymentor** [comment]
That is very strange, since the error seems to think your processor is not...

What is your model when you click "about mac"?

<img width="287" alt="image" src="https://user-images.githubusercontent.com/9071382/196784947-7cb9ba9c-e1b6-44f4-a5af-d0b25a249b39.png">

**Comment by timcampbell092** [comment]
Hi guys - same issue here on my M1 Macbook Air (Monterey 12.6). 
<img width="584" alt="Screen Shot 2022-10-19 at 1 02 26 PM" src="https://user-images.githubusercontent.com/116216043/196792374-4a3308e1-56d6-488e-bad9-172c7d5ea5ad.png">
Tried the install two days ago and getting the same errors. Have tried installing via DMG file and via the command line in terminal. 
Getting the exact same errors.
<img width="281" alt="Screen Shot 2022-10-18 at 9 52 15 AM" src="https://user-images.githubusercontent.com/116216043/196792099-627d902e-6cf7-473c-97f7-e3ed2a9827fa.png">
<img width="261" alt="Screen Shot 2022-10-19 at 1 04 35 PM" src="https://user-images.githubusercontent.com/116216043/196792772-7f7acc1a-b9bc-4c72-bd72-0cc247ebbfcb.png">
New to MacOS on a new Macbook Air.
The MacBook currently has the following apps installed:
DisplayLink Manager
MS Office
Adobe Premiere & Photoshop Elements 2021
Magnet
MS Edge (Still learning Safari!)

**Comment by jxnding** [comment]
<img width="237" alt="image" src="https://user-images.githubusercontent.com/10050512/196875674-d27b64ce-bc59-4f26-b2f6-ba9f50b6e05e.png">

**Comment by jxnding** [comment]
Cloning the repo, checking out the latest version tag, and building does seem to work. Will report later (at least adds "battery" as a background item) 
<img width="341" alt="image" src="https://user-images.githubusercontent.com/10050512/197421273-e0315519-3dee-4606-8dd0-bd765dbc16ab.png">

**Comment by merlinmah** [comment]
I get the same errors when Installing through `brew` in Ventura 13.0.1 on an M1 Max; I chalked it up to `/usr/local/bin` being hardcoded somewhere, instead of the `/opt/homebrew` prefix that `brew` uses by default. Installing via the Github shell script controls charging as expected, provided one remembers to use `sudo`. Thanks for making this!

**Comment by actuallymentor** [comment]
@merlinmah how would that path cause a CPU error?

**Comment by Tokarak** [comment]
It's not a cpu error, its a path error. Github search reveals all the hardcoded `/usr/local/bin/battery`.
https://github.com/actuallymentor/battery/search?q=%2Fusr%2Flocal%2Fbin%2Fbattery

**Comment by actuallymentor** [comment]
@Tokarak thanks for pointing that out. I think I fixed that path issue just now. Can you confirm it was fixed?

**Comment by phewitt** [comment]
looks like it fixed it for me. however the brew package and dmg still need a to include it. I had to clone the repo and run `./setup.sh` then install the GUI

**Comment by chujiluo** [comment]
facing the same error on M2. Is this expected?

**Comment by whiterock** [comment]
yeah the brew formulae need updating.

**Comment by actuallymentor** [comment]
@phewitt that is weird because the brew `dmg` clones the repo using the latest version...

**Comment by K-J-E** [comment]
hi, I am having this same error (installed through dmg on release page) and the command line commands do not work, so I am unable to use 'battery uninstall'. How could I uninstall the tool? thanks

**Comment by actuallymentor** [comment]
@K-J-E you can manually delete the files

**Comment by actuallymentor** [comment]
I just pushed a update that should fix a few issues, could you try to run `brew reinstall --cask battery` and see if that fixes it?

**Comment by actuallymentor** [comment]
Could you try the following things to help me debug:

**Debug trail 1: installing CLI only**

Instead of installing through brew, can you install through [these CLI instructions](https://github.com/actuallymentor/battery#installation-1) and show me your terminal output?

**Debug trail 2: running the app locally**

Can you try:

```shell
git clone git@github.com:actuallymentor/battery.git
cd battery/app
npm i
npm start
```

And show me what happens?

**Comment by KarstenS123** [comment]
I think my issue is the same in this issue report. If not, I can open a new one.

I tried just now to install the app by using the _battery-1.0.7-arm64.dmg_ file downloaded from the releases page.

My Mac is:

![Bildschirm­foto 2023-02-10 um 22 33 51](https://user-images.githubusercontent.com/30809115/218203954-5ea634a8-8b31-4778-abcb-8e82ebf73cad.png)

After enter the password for the "Updates" I get these error messages in this order:

<img width="306" alt="Bildschirm­foto 2023-02-10 um 22 31 48" src="https://user-images.githubusercontent.com/30809115/218204321-57a0b58e-480f-4bf5-9d7f-67756bb0c718.png">

<img width="308" alt="Bildschirm­foto 2023-02-10 um 22 32 05" src="https://user-images.githubusercontent.com/30809115/218204334-8a47aa56-acb4-4f5e-b1e8-18df7b175d13.png">

<img width="305" alt="Bildschirm­foto 2023-02-10 um 22 32 19" src="https://user-images.githubusercontent.com/30809115/218204342-4b57ac22-8d7c-48a0-a78b-b7589edf6c83.png">

<img width="307" alt="Bildschirm­foto 2023-02-10 um 22 32 31" src="https://user-images.githubusercontent.com/30809115/218204364-d3996ea4-100e-42db-b7c7-82a0b8df8527.png">

The battery icon is in the menu bar, but nothing happens when I click on it.

**Comment by Fiskheimer** [comment]
> I think my issue is the same in this issue report. If not, I can open a new one.
> 
> I tried just right now to install the app by using the _battery-1.0.7-arm64.dmg_ file downloaded from the releases page.
> 
> My Mac is:
> 
> ![Bildschirm­foto 2023-02-10 um 22 33 51](https://user-images.githubusercontent.com/30809115/218203954-5ea634a8-8b31-4778-abcb-8e82ebf73cad.png)
> 
> After enter the password for the "Updates" I get these error messages in this order:
> 
> <img alt="Bildschirm­foto 2023-02-10 um 22 31 48" width="306" src="https://user-images.githubusercontent.com/30809115/218204321-57a0b58e-480f-4bf5-9d7f-67756bb0c718.png">
> 
> <img alt="Bildschirm­foto 2023-02-10 um 22 32 05" width="308" src="https://user-images.githubusercontent.com/30809115/218204334-8a47aa56-acb4-4f5e-b1e8-18df7b175d13.png">
> 
> <img alt="Bildschirm­foto 2023-02-10 um 22 32 19" width="305" src="https://user-images.githubusercontent.com/30809115/218204342-4b57ac22-8d7c-48a0-a78b-b7589edf6c83.png">
> 
> <img alt="Bildschirm­foto 2023-02-10 um 22 32 31" width="307" src="https://user-images.githubusercontent.com/30809115/218204364-d3996ea4-100e-42db-b7c7-82a0b8df8527.png">
> 
> The battery icon is in the menu bar, but nothing happens when I click on it.

I get the same error messages and behavior on my MacBook Air M2.

<img width="392" alt="Screenshot 2023-02-11 at 09 03 53" src="https://user-images.githubusercontent.com/4624697/218247626-70e68c56-8c62-4813-8d1c-78b66d550915.png">

**Comment by markspercyspencer** [comment]
I have the exact same error messages when trying to install Battery.dmg on my M1 MacBook Air. 
<img width="288" alt="Screenshot 2023-02-12 at 02 00 23" src="https://user-images.githubusercontent.com/125167586/218289050-42f20cee-60d1-4d5c-974b-22e44006ddae.png">
<img width="288" alt="Screenshot 2023-02-12 at 02 00 27" src="https://user-images.githubusercontent.com/125167586/218289053-4c51dfe4-4702-4f53-89c1-849ccb5a64f2.png">
<img width="288" alt="Screenshot 2023-02-12 at 02 00 31" src="https://user-images.githubusercontent.com/125167586/218289054-05b08a66-5e98-4190-8bae-fe9ac2cca8a6.png">
<img width="288" alt="Screenshot 2023-02-12 at 02 00 34" src="https://user-images.githubusercontent.com/125167586/218289055-052ab632-5c0f-4432-90ed-6da74ff7aeef.png">
<img width="288" alt="Screenshot 2023-02-12 at 02 05 34" src="https://user-images.githubusercontent.com/125167586/218289067-dff26b55-104b-4733-9689-4f200f80a9c8.png">

**Comment by actuallymentor** [comment]
I believe we found the issue in #48!

Can someone (@jxnding?) with this issue please install [this v1.0.8 pre-release](https://github.com/actuallymentor/battery/releases/tag/v1.0.8-beta) and let me known if that solves the issue?

**Comment by aresYio** [comment]
It doesn't work, even with the 1.08 version

**Comment by michkz** [comment]
I am also experiencing the same error: "error installing battery limited: undefined” after installing through brew. Im currently on the latest release (v1.2.1). The CLI installation does successfully install the application, but the commands “battery maintain 80” and “battery charging off” do not seem to show the expected visual effect on the battery icon. Also running on a M1 mac
