### ISSUE TITLE
Battery stops at 81%

### ISSUE THREAD

**Issue by mihainigrini** [actuallymentor/battery#162]
Installed but ...
1. Clicked on enable battery limit
but
Battery charging stops at 81%? - MacBookPro M2 Max stock, any ideea why it does not stop 80% ? Could other or previous apps have done something to cause this behaviour ?

<img width="542" alt="image" src="https://github.com/actuallymentor/battery/assets/4497966/829b897b-3bef-4dd2-b9d7-462ca9254a32">

(read all open issues and decided to do this)
Disabled 80% from System>Battery 
<img width="481" alt="image" src="https://github.com/actuallymentor/battery/assets/4497966/a2ee1599-74ee-40b7-bc5d-a16cf9b08aca">
Will update if anything changes

**Comment by mihainigrini** [comment]
So, after doing what I mentioned, the battery indicator remains at 80%

<img width="355" alt="image" src="https://github.com/actuallymentor/battery/assets/4497966/f21c06bd-06c7-43ea-8a89-cf223fbb10b4">
Just remember to disable in Battery the Optimised Battery Charging setting
<img width="587" alt="image" src="https://github.com/actuallymentor/battery/assets/4497966/b88504dc-9826-425e-ae28-b154a50c7a3a">

**Comment by mihainigrini** [comment]
If it goes to sleep, yet again it goes up  to 81 %
<img width="375" alt="image" src="https://github.com/actuallymentor/battery/assets/4497966/e64c684a-aed5-4a90-b5de-1b29b444824d">

**Comment by pdcastro** [comment]
> If it goes to sleep, yet again it goes up to 81 %

To be fair, for some time I was using the popular [AlDente app](https://apphousekitchen.com) on an M2 MacBook Air and AlDente also had this issue where the battery charged a bit beyond the configured limit, usually between 1% and 5% above the limit, especially while the laptop was sleeping while plugged in. I suspect it is _not_ some simple logic bug in AlDente or in this `battery` tool, but rather a case of the Mac itself not quite always doing what the [SMC](https://en.wikipedia.org/wiki/System_Management_Controller) settings are meant to do. Another potential contributing factor — I guess — is that between going to sleep and waking up 10 hours later, the battery voltage changes a bit due to changes in temperature and chemistry and macOS re-evaluates what it translates to in terms of state of charge. The physical world can be messy, right? :-) Anyway, just a guess.

My workaround is to set the limit a few percentage points below the desired state of charge. For example, I used to set AlDente to 75% so that typically the battery charge would reach 77-79%.
